version: "3.9"

services:
  backend:
    build: ./iot-backend
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=mysecret
      - MONGO_URI=mongodb://mongo:27017/iotdb
    depends_on:
      - mongo

  frontend:
    build: ./iot-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
